// Generated by CoffeeScript 1.10.0
(function() {
  var Method, YAML, fromJSON, fromYAML, isObject, isString, json, ref, toJSON, toYAML, yaml;

  ref = require("fairmont"), isString = ref.isString, isObject = ref.isObject, fromJSON = ref.fromJSON, toJSON = ref.toJSON, Method = ref.Method;

  YAML = require("js-yaml");

  toYAML = function(data) {
    return YAML.safeDump(data);
  };

  fromYAML = function(yaml) {
    return YAML.safeLoad(yaml);
  };

  yaml = Method.create();

  Method.define(yaml, isString, fromYAML);

  Method.define(yaml, isObject, toYAML);

  yaml.from = fromYAML;

  yaml.to = toYAML;

  json = Method.create();

  Method.define(json, isString, fromJSON);

  Method.define(json, isObject, toJSON);

  json.from = fromJSON;

  json.to = toJSON;

  module.exports = {
    json: json,
    yaml: yaml
  };

}).call(this);
